server:
    port: 8085
    servlet:
        context-path: /api
spring:
    application:
        name: gd_service  #应用名
        transactiontimeout: 600 #全局事务超时时间，单位秒
    main:
        allow-bean-definition-overriding: true #发现相同名称的Bean会覆盖之前的
    #设置Tomcat服务器文件传输大小，默认10M
    servlet:
        multipart:
            max-file-size: 30MB
            max-request-size: 50MB
    datasource:  #数据源
        primary:
            type: com.zaxxer.hikari.HikariDataSource
            driver-class-name: com.mysql.cj.jdbc.Driver
            name: primaryDataSource
            #阿里云云服务器mysql
#            jdbc_url: jdbc:mysql://47.94.156.155:3306/gd_plan?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
#            username: gd_plan
#            password: ENC(bzjNsn1h4rZzoi25WPRPNHzYTMasifMy344FSvoX6ec=)
            #本地Mysql
            jdbc_url: jdbc:mysql://localhost:3306/gd_plan?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
            username: root
            password: ENC(3ikov0SrW5E6M8J3OTeDW8mu1wTT7+NM)
            #连接池名
            pool-name: DatahikariCP
            #最小连接数
            minimun-idle: 5
            #空闲连接存活最大时间，默认600000（60分钟）
            idle-timeout: 60000
            # 最大连接数,默认10
            maximun-pool-size: 10
            # 从连接池返回的连接自动提交
            auto-commit: true
            # 连接最大存活时间，0表示永久存活，默认180000（30分钟）
            max-lifetime: 180000
            # 连接超时时间，默认30000（30秒）
            connection-timeout: 30000
            #测试连接是否可用的查询语句
#            connection-test-query: SSLECT 1
        secondary:
            type: com.zaxxer.hikari.HikariDataSource
            driver-class-name: com.mysql.cj.jdbc.Driver
            name: secondaryDataSource
            jdbc_url: jdbc:mysql://47.94.156.155:3306/guagua?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
            username: guagua
            password: 15912504206
#        hikari:
            #连接池名
            pool-name: DatahikariCP
            #最小连接数
            minimun-idle: 5
            #空闲连接存活最大时间，默认600000（60分钟）
            idle-timeout: 60000
            # 最大连接数,默认10
            maximun-pool-size: 10
            # 从连接池返回的连接自动提交
            auto-commit: true
            # 连接最大存活时间，0表示永久存活，默认180000（30分钟）
            max-lifetime: 180000
            # 连接超时时间，默认30000（30秒）
            connection-timeout: 30000
            #测试连接是否可用的查询语句
#            connection-test-query: SSLECT 1
    #jpa
    jpa:
        hibernate:
            ddl-auto: update #自动更新
#            dialect: org.hibernate.dialect.MySQL8Dialect #指定默认的存储引擎为InnoDB
        show-sql: true  #日志中显示sql语句
        database: mysql
        open-in-view: false
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #默认使用MyISAM引擎,改为使用innodb引擎建表,Mysql数据库有两种引擎，注意要使用支持事务的引擎，比如innodb，如果是MyISAM，事务是不起作用的

    redis:  #redis缓存
        database: 2         #连接工厂使用的数据库索引,指定数据库
#        host: 47.94.156.155
        host: 127.0.0.1
        port: 6379
        password:   # Redis服务器连接密码（默认为空）
        pool:
            max-active: 200 #连接池最大连接数（使用负值表示没有限制）
            max-idle: 10    #连接池中最大空闲连接
            max-wait: -1    #连接池最大阻塞等待时间（使用负值表示没有限制）
            min-idle: 0     # 连接池中的最小空闲连接
        timeout: 1000       # 连接超时时间（毫秒）


    #热部署配置
    devtools:
        restart:
            enabled: true #设置开启热部署
            additional-paths: src/main/java #重启目录
        freemarker:
            cache: false #页面不加载缓存，修改即时生效


#swagger接口文档配置
swagger:
    basePackage: com.gd   #扫描路径
    title: 高校毕业设计管理系统后端接口文档
    author: 毕设小分队(岑徐节、唐小林、陈佳俊)
    url: http://nntsix.work:8085/doc.html
    email: 1143229050@qq.com
    description: 基于Springboot+Vue的高校毕业设计管理系统
    version: 0.0.1



#jasypt加解密密码
jasypt:
    encryptor:
        password: zagjdhjkasjkd

# ftp配置
ftp:
    ftpIp: 47.94.156.155 #ftp服务器IP地址
    ftpPort: 21 #端口号
    ftpUser: gd_plan #用户名
    ftpPassword: aTSsfWwhNy2XFNwm #密码
    FtpSavePase: /upload #存储路径

#lombok日志输出配置
loging:
    config: classpath:logback-spring.xml
    path: /www/wwwroot/gd_plan/gd_plan/log
    file: gd_plan_log.log

#过滤器流处理配置
stream:
    # 过滤开关
    enabled: true
    # 排除链接（多个用逗号分隔）
    excludes: /api/*upload,/api/file/upload*
    # 匹配链接
    urlPatterns: /api/*



